dist: focal

language: python

python:
  - "2.7"
  - "3.7"

env:
  global:
    - TZ=America/New_York
    - NUO_DOWNLOAD=https://ce-downloads.nuohub.org
    - NUO_ARCH=linux.x86_64
    - NUO_SET_TLS=disable

notifications:
  recipients:
    - drivers@nuodb.com

before_install:
  - echo madvise | sudo tee /sys/kernel/mm/transparent_hugepage/enabled >/dev/null
  - echo madvise | sudo tee /sys/kernel/mm/transparent_hugepage/defrag >/dev/null
  - wget -q "$NUO_DOWNLOAD/supportedversions.txt" --output-document=/tmp/supportedversions.txt
  - wget -q "$NUO_DOWNLOAD/nuodb-$(tail -n1 /tmp/supportedversions.txt).$NUO_ARCH.tar.gz" --output-document=/var/tmp/nuodb.tgz
  - mkdir -p "$HOME/nuodb"
  - cd "$HOME/nuodb" && tar xzf /var/tmp/nuodb.tgz --strip-components 1
  - echo "NuoDB Version:" && "$HOME/nuodb/bin/nuodb" --version

install:
  - make install

before_script:
  - "$HOME/nuodb/etc/nuoadmin" tls $NUO_SET_TLS
  - "$HOME/nuodb/etc/nuoadmin" start

script:
  - make test NUODB_HOME="$HOME/nuodb"

after_failure:
  - cat "$HOME"/nuodb/var/log/nuoadmin.log*
  - grep ssl "$HOME/nuodb/etc/nuoadmin.conf"
