dist: xenial

language: python

python:
  - "2.7"
  - "3.7"

env:
  global:
    - TZ=America/New_York
    - NUO_DOWNLOAD=https://ce-downloads.nuohub.org
    - NUO_ADD_DOMAIN_PASS=yes
    - NUO_START_AGENT=yes
    - NUODB_HOME=/opt/nuodb

notifications:
  recipients:
    - drivers@nuodb.com

before_install:
  - echo madvise | sudo tee /sys/kernel/mm/transparent_hugepage/enabled >/dev/null
  - echo madvise | sudo tee /sys/kernel/mm/transparent_hugepage/defrag >/dev/null
  - wget -q "${NUO_DOWNLOAD}/supportedversions.txt" --output-document=/tmp/supportedversions.txt
  - wget -q "${NUO_DOWNLOAD}/nuodb-ce_$(tail -n1 /tmp/supportedversions.txt)_amd64.deb" --output-document=/var/tmp/nuodb.deb
  - sudo dpkg -i /var/tmp/nuodb.deb

install:
  - make install

before_script:
  - if [ "$NUO_ADD_DOMAIN_PASS" = yes ]; then printf '\ndomainPassword = bird\n' | sudo tee -a "$NUODB_HOME"/etc/default.properties >/dev/null; fi
  - if [ "$NUO_START_AGENT" = yes ]; then sudo service nuoagent start; fi

script:
  - make test

after_failure:
  - cat "$NUODB_HOME"/etc/default.properties
  - cat /var/log/nuodb/agent.log
